version: '3.7'

services:
  django:
    build: .
    container_name: ct21-django-dev-container
    image: ct21-django-dev-image
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/code
#      #- ../ct-volumes/bucket:/ct-bucket
    command: /srv/start
    restart: always
    #env_file:
    #  - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=hast
  postgres:
    image: postgres:13-alpine
    #build:
    #  context: .
    #  dockerfile: ./compose/production/postgres/Dockerfile
    #image: ct-postgres-image
    container_name: ct21-postgres-container
    restart: always
    volumes:
      - ../ct21-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../ctt21-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=hast
      - PGDATA=/var/lib/postgresql/data/pgdata
#  redis:
#    image: redis:6-alpine
#    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../ct21-volumes/mongo_data:/data/db
      - ../ct21-volumes/bucket:/bucket
    expose:
      - 27017
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
