version: '3.7'

services:
  django:
    build: .
    container_name: ct21-django-dev-container
    image: ct21-django-dev-image
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../ct21-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    #env_file:
    #  - .env
    environment:
      - WEB_ENV=dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
  postgres:
    image: postgres:13-alpine
    #build:
    #  context: .
    #  dockerfile: ./compose/production/postgres/Dockerfile
    #image: ct-postgres-image
    container_name: ct21-postgres-container
    restart: always
    volumes:
      - ../ct21-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../ct21-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
      - PGDATA=/var/lib/postgresql/data/pgdata
    #env_file:
    #  - .env
  redis:
    image: redis:6-alpine
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
