version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ct21-django-prod-container
    image: ct21-django-prod-image
    expose:
      - 8001
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../ct21-volumes/static:/ct21-volumes/static
      - ../ct21-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    #env_file:
    #  - .env
    environment:
      - WEB_ENV=prod
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
  postgres:
    image: postgres:13-alpine
    container_name: ct21-postgres-container
    restart: always
    volumes:
      - ../ct21-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../ct21-volumes/bucket:/bucket
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=cameratrap
      - PGDATA=/var/lib/postgresql/data/pgdata
#  redis:
#    image: redis:6-alpine
#    restart: always
  nginx:
    image: nginx:1.19.10-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./scripts/nginx-django.conf:/etc/nginx/conf.d/ct21.conf
      - ../ct21-volumes/static:/ct21-volumes/static
      #- ../basdb-volumes/media:/basdb-volumes/media
